# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:  # Establece las variables de entorno para tu aplicación
  MONGO_DB_USR: ADMIN
  MONGO_DB_PWD: ADMIN
  MONGO_DB_HOST: localhost
  MONGO_DB_PORT: 27017

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        mongodb-version: ['6.0']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/


    # se puede borrar
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: --name monguito

    steps:
    - name: Git Checkout
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'


    - name: Wait for MongoDB to be ready
      run: |
          while ! nc -z localhost 27017; do sleep 1; done
        timeout-minutes: 2

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
        mongodb-port: 27017
        mongodb-username: ADMIN
        mongodb-password: ADMIN
        mongodb-db: Nota

    - name : Install dependencies
      run: npm ci

    - run: npm run build --if-present
    - run: npm test
