name: Run tests with authentication

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        mongodb-version: ['4.2', '4.4', '5.0', '6.0']

    steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
        mongodb-replica-set: test-rs
        mongodb-port: 27017

    - name: Install dependencies
      run: npm ci

    - name: Configure Node.js environment variables
      run: |
        echo "MONGO_DB_USR=ADMIN" >> $GITHUB_ENV
        echo "MONGO_DB_PWD=ADMIN" >> $GITHUB_ENV
        echo "MONGO_DB_HOST=localhost" >> $GITHUB_ENV
        echo "MONGO_DB_PORT=27017" >> $GITHUB_ENV

    - name: Run tests
      run: npm test