# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        mongodb-version: ['4.2', '4.4', '5.0', '7.0']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        
    env:  # Establece las variables de entorno para tu aplicación
      MONGO_DB_USR: myuser
      MONGO_DB_PWD: mypassword
      MONGO_DB_HOST: localhost
      MONGO_DB_PORT: 27017
      
    steps:
    - name: Git checkout
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
        mongodb-username: ADMIN
        mongodb-password: ADMIN
        mongodb-db: Nota
        mongodb-port: 27017

        
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
